// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251220184402_mig1")]
    partial class mig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebApplication1.Models.Album", b =>
                {
                    b.Property<int>("id_album")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id_album");

                    b.ToTable("Albums", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.Album_Capture", b =>
                {
                    b.Property<int>("id_album")
                        .HasColumnType("int");

                    b.Property<int>("id_capture")
                        .HasColumnType("int");

                    b.HasKey("id_album", "id_capture");

                    b.HasIndex("id_capture");

                    b.ToTable("Albums_Captures", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.Capture", b =>
                {
                    b.Property<int>("id_capture")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("batterie")
                        .HasColumnType("int");

                    b.Property<string>("chemin_image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("date_capture")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("favoris")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("resolution")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("taille_image")
                        .HasColumnType("int");

                    b.HasKey("id_capture");

                    b.ToTable("Capture", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.Album_Capture", b =>
                {
                    b.HasOne("WebApplication1.Models.Album", "Album")
                        .WithMany("Album_Captures")
                        .HasForeignKey("id_album")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.Capture", "Capture")
                        .WithMany("Album_Captures")
                        .HasForeignKey("id_capture")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Capture");
                });

            modelBuilder.Entity("WebApplication1.Models.Album", b =>
                {
                    b.Navigation("Album_Captures");
                });

            modelBuilder.Entity("WebApplication1.Models.Capture", b =>
                {
                    b.Navigation("Album_Captures");
                });
#pragma warning restore 612, 618
        }
    }
}
